# Variables:
# - API_PORT (default: 2222): Port to expose for notes API
# - WEB_PORT (default: 4444): Port to expose for notes web UI

services:
  api:
    build:
      context: .
      dockerfile_inline: |
        FROM notes-api/api
        COPY ./notes.sqlite /app/data
    ports:
      - ${API_PORT:-2222}:80
    environment:
      NOTES_API_DB_DIR: /app/data
      NOTES_API_PORT: 80
      NOTES_API_DISABLE_AUTH: 1
  web:
    build:
      context: .
    ports:
      - ${WEB_PORT:-4444}:80
    environment:
      NOTES_WEB_PORT: 80
      NOTES_WEB_STATIC_FILES_DIR: /app/assets-shared
      # NOTES_WEB_AUTH_PROVIDER_URL: http://localhost:8080/realms/notes
    volumes:
      - ./assets:/app/assets-shared