# Variables:
# - API_PORT (default: 2222): Port to expose for notes API
# - WEB_PORT (default: 4444): Port to expose for notes web UI
# - DISABLE_AUTH (default: <none>): If a value is provided, turn off authentication on notes services

services:
  auth:
    build:
      context: docker-local-auth
    hostname: notes-auth.local
    ports:
      - 8080:8080
  api:
    depends_on:
      - auth
    build:
      context: .
      dockerfile_inline: |
        FROM notes-api/api
        COPY ./notes.sqlite /app/data
    ports:
      - ${API_PORT:-2222}:80
    environment:
      NOTES_API_DB_DIR: /app/data
      NOTES_API_PORT: 80
      NOTES_API_AUTH_PROVIDER_URL: http://notes-auth.local:8080/realms/notes
      NOTES_API_REDIRECT_URL: http://localhost:${API_PORT:-2222}/notes/auth/callback
      NOTES_API_DISABLE_AUTH: ${DISABLE_AUTH}
  web:
    depends_on:
      - auth
    build:
      context: .
    ports:
      - ${WEB_PORT:-4444}:80
    environment:
      NOTES_WEB_PORT: 80
      NOTES_WEB_STATIC_FILES_DIR: /app/assets-shared
      NOTES_WEB_API_URL: http://localhost:${API_PORT:-2222}/notes
      NOTES_WEB_AUTH_PROVIDER_URL: http://notes-auth.local:8080/realms/notes
      NOTES_WEB_REDIRECT_URL: http://localhost:${WEB_PORT:-4444}/auth/callback
      NOTES_WEB_DISABLE_AUTH: ${DISABLE_AUTH}
    volumes:
      - ./assets:/app/assets-shared