# Variables:
# - WEB_PORT (default: 4444): Port to expose for notes web UI
# - DISABLE_AUTH (default: <none>): If a value is provided, turn off authentication on web service

services:
  web:
    build:
      context: .
    ports:
      - ${WEB_PORT:-4444}:80
    environment:
      NOTES_WEB_PORT: 80
      NOTES_WEB_STATIC_FILES_DIR: /app/assets-shared
      NOTES_WEB_API_URL: https://api.notes.quemot.dev/notes
      NOTES_WEB_AUTH_PROVIDER_URL: https://auth.notes.quemot.dev/realms/notes
      NOTES_WEB_REDIRECT_URL: http://localhost:${WEB_PORT:-4444}/auth/callback
      NOTES_WEB_DISABLE_AUTH: ${DISABLE_AUTH}
    volumes:
      - ./assets:/app/assets-shared